from SupaDupaResult import SupaDupaResult
import Writer

defaultClassTypes = {
    str(unicode) : "NSString",
    str(list) : "NSArray",
    str(int) : "NSNumber",
    str(float) : "NSNumber",
    str(bool) : "NSNumber",
    str(None.__class__) : "id"
}

class Writer(Writer.Writer):
    def __init__(self, classDict, outputDir=None):
        self.classDict = dict([(key.capitalize(), val) for key, val in classDict.iteritems()])
        self.outputDir = outputDir

    def realPropertyType(self, prop, inferred):
        if prop.capitalize() in self.classDict.keys():
            return prop.capitalize()
        return inferred

    def getResult(self):
        if self.outputDir is None:
            result = SupaDupaResult(self.getForwardDec())
        else:
            result = SupaDupaResult("// This class generated by Supa Dupa!")

        # TODO NEED TO HAVE A REQUIREMENTS DEP GRAPH
        for className, props in self.classDict.iteritems():
            result.addFile(className + '.h', self.getClassHeader(className))
            result.addFile(className + '.m', self.getClassImpl(className))
        return result
    
    def getForwardDec(self):
        return "@class " + ", ".join(self.classDict.keys()) + ";"

    def getClassHeader(self, className):
        top = "@interface {} : NSObject".format(className)
        bottom = "@end"
        middle = []
        for propName, propType in self.classDict[className].iteritems():
            propertyType = self.realPropertyType(propName, propType)
            propertyFormatString = "@property(nonatomic,strong){} *{};"
            middle.append(propertyFormatString.format(propertyType, propName))
        return '\n'.join([top, '\n'.join(middle), bottom])

    def getClassImpl(self, className):
        return "@implementation {}\n@end".format(className)

